spring.application.name=paymentservice
server.port=8085
razorpay.keyId=rzp_test_SROjgZhSQAE0Vz
razorpay.keySecret=qtus52HfqINuRowFlar0CkpZ

stripe.apiKey = sk_test_51TBypER03QLZwHnOG8GqVyiDWFfLkMizHGehb9EFI5vNwAEo7MBvByFu2dRZGH7YyOtKu7skbHU4tcVD3yWaiPwm00bFw7FWC2

stripe.webhook.secret = whsec_nt4hdtiIRpyNHr9vJxNxNAYJmJsuEYgG

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.main.allow-bean-definition-overriding=true
